services:
  app:
    build: .
    container_name: edu_platform_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./uploads:/usr/src/app/uploads # Assuming uploads directory exists in the app
      - ../frontend/public/webgl-tasks:/usr/src/app/frontend/public/webgl-tasks
    environment:
      - NODE_ENV=production
    image: beliaa/labx


  mongo:
    image: mongo:6
    container_name: edu_platform_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: edu_platform_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: